apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: consumer
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: consumer

  template:
    metadata:
      creationTimestamp: null
      labels:
        service: consumer
      name: consumer
    spec:
      containers:
      - image: yfe404/nd064-udaconnect-consumer:latest
        name: consumer
        imagePullPolicy: Always
        restartPolicy: Always
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_NAME
          value: postgres
        - name: DB_PASSWORD
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_USERNAME
          value: postgres
        - name: KAFKA_HOST
          value: kafka
        - name: KAFKA_PORT
          value: "9092"
        - name: TOPIC_NAME
          value: locations
