apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      service: kafka
  template:
    metadata:
      labels:
        service: kafka
    spec:
      containers:
        - image: bitnami/kafka:2.8.1
          name: kafka
          ports:
            - containerPort: 9092
          env:
          - name: ALLOW_PLAINTEXT_LISTENER
            valueFrom:
              configMapKeyRef:
                name: zookeeper-env
                key: ALLOW_PLAINTEXT_LISTENER
          - name: KAFKA_CFG_ADVERTISED_LISTENERS
            valueFrom:
              configMapKeyRef:
                name: zookeeper-env
                key: KAFKA_CFG_ADVERTISED_LISTENERS
          - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
            valueFrom:
              configMapKeyRef:
                name: zookeeper-env
                key: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
          - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
            valueFrom:
              configMapKeyRef:
                name: zookeeper-env
                key: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
          - name: KAFKA_CFG_LISTENERS
            valueFrom:
              configMapKeyRef:
                name: zookeeper-env
                key: KAFKA_CFG_LISTENERS
          - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
            valueFrom:
              configMapKeyRef:
                name: zookeeper-env
                key: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          - name: KAFKA_CFG_ZOOKEEPER_CONNECT
            valueFrom:
              configMapKeyRef:
                name: zookeeper-env
                key: KAFKA_CFG_ZOOKEEPER_CONNECT
      restartPolicy: Always
