apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      service: kafka
  template:
    metadata:
      labels:
        service: kafka
    spec:
      containers:
        - image: bitnami/kafka:2.8.1
          name: kafka
          ports:
            - containerPort: 9092
          restartPolicy: Always
          env:
          - name: ALLOW_PLAINTEXT_LISTENER
            value: "yes"
          - name: KAFKA_CFG_ADVERTISED_LISTENERS
            value: INSIDE://kafka:9092
          - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
            value: "true"
          - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
            value: INSIDE
          - name: KAFKA_CFG_LISTENERS
            value: INSIDE://0.0.0.0:9092
          - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
            value: INSIDE:PLAINTEXT
          - name: KAFKA_CFG_ZOOKEEPER_CONNECT
            value: zookeeper:2181
