apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: producer
  name: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: producer

  template:
    metadata:
      labels:
        service: producer
    spec:
      containers:
        - image: yfe404/nd064-udaconnect-producer:latest
          name: producer
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
          env:
            - name: KAFKA_HOST
              value: kafka
            - name: KAFKA_PORT
              value: "9092"
            - name: TOPIC_NAME
              value: locations
      restartPolicy: Always
