apiVersion: v1
kind: Service
metadata:
  labels:
    service: producer
  name: producer
spec:
  ports:
  - name: "50051"
    port: 50051
    nodePort: 30002	
    targetPort: 50051
  selector:
    service: producer
  type: NodePort
status:
  loadBalancer: {}
