apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: producer
  name: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: producer

  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: producer
    spec:
      containers:
      - env:
        - name: KAFKA_HOST
          value: kafka
        - name: KAFKA_PORT
          value: "9092"
        - name: TOPIC_NAME
          value: locations
      - image: yfe404/nd064-udaconnect-producer:latest
        name: producer
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
        resources: {}
      restartPolicy: Always
status: {}
