apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: producer
  name: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: producer

  template:
    metadata:
      labels:
        service: producer
    spec:
      containers:
        - image: yfe404/nd064-udaconnect-producer:latest
          name: producer
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
          env:
          - name: KAFKA_HOST
            valueFrom:
              configMapKeyRef:
                name: kafka-env
                key: KAFKA_HOST
          - name: KAFKA_PORT
            valueFrom:
              configMapKeyRef:
                name: kafka-env
                key: KAFKA_PORT
          - name: TOPIC_NAME
            valueFrom:
              configMapKeyRef:
                name: kafka-env
                key: TOPIC_NAME
      restartPolicy: Always
