apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: zookeeper
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      service: zookeeper
  template:
    metadata:
      labels:
        service: zookeeper
    spec:
      containers:
        - image: bitnami/zookeeper:latest
          name: zookeeper
          ports:
            - containerPort: 2181
          restartPolicy: Always
          env:
          - name: ALLOW_ANONYMOUS_LOGIN
            value: "yes"
