on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

name: Push images on Docker hub

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build, tag, and push the image to Docker Registry
        id: build-image
        run: |
          cd modules/frontend
          docker build -t yfe/nd064-udaconnect-app:latest .
          echo "Pushing image to docker registry..."
          docker push yfe/nd064-udaconnect-app:latest
